// <auto-generated />
namespace SHASApplication.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class checkPoint4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(checkPoint4));
        
        string IMigrationMetadata.Id
        {
            get { return "201304272045270_checkPoint4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
