//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHASApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class configsmartplug
    {
        public int ID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string DeviceThreshold { get; set; }
    
        public virtual configdevicestatu configdevicestatu { get; set; }
        public virtual device device { get; set; }
    }
}
