//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHASApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class configsmartshower
    {
        public int ID { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
