//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHASApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class configdevicestatu
    {
        public configdevicestatu()
        {
            this.configsmartplugs = new HashSet<configsmartplug>();
        }
    
        public int ID { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<configsmartplug> configsmartplugs { get; set; }
    }
}
