//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHASApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class logsthermostat
    {
        public int ID { get; set; }
        public string CurrentTemperature { get; set; }
        public string DesiredTemperature { get; set; }
        public string DeviceStatus { get; set; }
        public string OperatingMode { get; set; }
        public string EnergyMode { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
