//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHASApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shasEntities : DbContext
    {
        public shasEntities()
            : base("name=shasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<configdevicestatu> configdevicestatus { get; set; }
        public DbSet<configsmartplug> configsmartplugs { get; set; }
        public DbSet<configsmartthermostat> configsmartthermostats { get; set; }
        public DbSet<device> devices { get; set; }
        public DbSet<logsmartmeter> logsmartmeters { get; set; }
        public DbSet<logsmartrefrigerator> logsmartrefrigerators { get; set; }
        public DbSet<logsmartshower> logsmartshowers { get; set; }
        public DbSet<logsmartsprinkler> logsmartsprinklers { get; set; }
        public DbSet<logsmartwaterheater> logsmartwaterheaters { get; set; }
        public DbSet<logsthermostat> logsthermostats { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<configsmartshower> configsmartshowers { get; set; }
        public DbSet<configsmartsprinkler> configsmartsprinklers { get; set; }
        public DbSet<configsmartrefrigerator> configsmartrefrigerators { get; set; }
        public DbSet<configsmartwaterheater> configsmartwaterheaters { get; set; }
        public DbSet<configemergencyauthority> configemergencyauthorities { get; set; }
    }
}
